stages:
  - build

  
#----------------------------------------------------------
#  Rest_Assured_Mangops - Servidor IA
#----------------------------------------------------------

Build_Stage:
  stage: build
  script:
    - cd /home/ia/microservicios/endpoint_test_mangops && git reset --hard
    - cd /home/ia/microservicios/endpoint_test_mangops && git pull origin master
  only:
  - master
  tags:
  - server-ia
